import os
import json
from datetime import datetime
from typing import Dict, List, Any

class ReportGenerator:
    """Generates detailed compliance reports with improvement suggestions."""
    
    @staticmethod
    def generate_markdown(audit_trail: List[Dict], project_info: Dict) -> str:
        report = []
        report.append(f"# RaiFlow Compliance Report")
        report.append(f"**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report.append(f"**Project Name:** {project_info.get('name', 'AI Project')}")
        report.append(f"---\n")
        
        report.append(f"## 📊 Executive Summary")
        report.append(f"The project was analyzed for compliance with the **EU AI Act**. Below are the findings based on the latest audit trail.\n")
        
        # Aggregate scores
        if not audit_trail:
            report.append("> [!WARNING]\n> No audit events found. Run a check to generate data.")
            return "\n".join(report)
            
        last_event = audit_trail[-1]
        audit_report = last_event.get("audit_report", {})
        sections = audit_report.get("sections", [])
        
        report.append(f"### Key Findings")
        for section in sections:
            section_id = section.get("section_id")
            # Calculate avg score for section
            scores = [stage.get("final_score", 0) for stage in section.get("stages", [])]
            avg_score = sum(scores) / len(scores) if scores else 0
            
            status = "✅ PASS" if avg_score >= 0.75 else "⚠️ PARTIAL" if avg_score >= 0.5 else "❌ FAIL"
            report.append(f"- **{section_id}**: {status} (Score: {avg_score:.2f})")
            
        report.append(f"\n## 🔧 Recommended Improvements")
        
        for section in sections:
            for stage in section.get("stages", []):
                if stage.get("final_score", 1.0) < 0.8:
                    stage_name = stage.get("stage")
                    critique = stage.get("history", [{}])[-1].get("critique", "No details available.")
                    
                    report.append(f"### Fix for {section.get('section_id')} ({stage_name})")
                    report.append(f"> **Issue:** {critique}")
                    report.append(f"**Action Plan:**")
                    if "Article 12" in section.get("section_id"):
                        report.append("- Implement automated session logging for at least 6 months.")
                        report.append("- Ensure logs include timestamps, User IDs, and model parameters.")
                    elif "Article 13" in section.get("section_id"):
                        report.append("- Generate a system-card with accuracy and limitation metrics.")
                        report.append("- Add a 'Why did the AI say this?' feature for transparency.")
                    else:
                        report.append("- Update technical documentation to align with Annex IV requirements.")
                        report.append("- Perform a bias audit on your training datasets.")

        report.append(f"\n---\n*Report generated by RaiFlow - The Regulatory AI Guardrail Framework.*")
        return "\n".join(report)
