import os
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any

from raiflow.gate import CheckResult
from raiflow.manifest import RaiFlowManifest

SCHEMA_VERSION = "1.0"


def _get_git_sha() -> str:
    try:
        import subprocess
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], text=True
        ).strip()
    except Exception:
        return "unknown"


def build_report(
    stage: str,
    manifest: RaiFlowManifest,
    checks: List[CheckResult],
    git_sha: str = None,
    enable_llm_checks: bool = False,
) -> dict:
    """Build a structured compliance report dict (Requirements 9.1, 9.2, 10.4)."""
    overall = "pass" if all(c.status != "fail" for c in checks) else "fail"
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "git_sha": git_sha or _get_git_sha(),
        "stage": stage,
        "system_name": manifest.system_name,
        "overall_status": overall,
        "evaluation_mode": "semantic" if enable_llm_checks else "static",
        "checks": [
            {
                "article_id": c.article_id,
                "rule_id": c.rule_id,
                "check_name": c.check_name,
                "status": c.status,
                "score": c.score,
                "threshold": c.threshold,
                "remediation_hint": c.remediation_hint,
            }
            for c in checks
        ],
    }


def write_report(report: dict, output_path: str) -> None:
    """Write report dict as indented JSON, creating parent dirs as needed (Requirement 9.4)."""
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w") as f:
        json.dump(report, f, indent=2, sort_keys=True)

class ReportGenerator:
    """Generates detailed compliance reports with improvement suggestions."""
    
    @staticmethod
    def generate_markdown(audit_trail: List[Dict], project_info: Dict) -> str:
        report = []
        report.append(f"# RaiFlow Compliance Report")
        report.append(f"**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report.append(f"**Project Name:** {project_info.get('name', 'AI Project')}")
        report.append(f"---\n")
        
        report.append(f"## 📊 Executive Summary")
        report.append(f"The project was analyzed for compliance with the **EU AI Act**. Below are the findings based on the latest audit trail.\n")
        
        # Aggregate scores
        if not audit_trail:
            report.append("> [!WARNING]\n> No audit events found. Run a check to generate data.")
            return "\n".join(report)
            
        last_event = audit_trail[-1]
        audit_report = last_event.get("audit_report", {})
        sections = audit_report.get("sections", [])
        
        report.append(f"### Key Findings")
        for section in sections:
            section_id = section.get("section_id")
            # Calculate avg score for section
            scores = [stage.get("final_score", 0) for stage in section.get("stages", [])]
            avg_score = sum(scores) / len(scores) if scores else 0
            
            status = "✅ PASS" if avg_score >= 0.75 else "⚠️ PARTIAL" if avg_score >= 0.5 else "❌ FAIL"
            report.append(f"- **{section_id}**: {status} (Score: {avg_score:.2f})")
            
        report.append(f"\n## 🔧 Recommended Improvements")
        
        for section in sections:
            for stage in section.get("stages", []):
                if stage.get("final_score", 1.0) < 0.8:
                    stage_name = stage.get("stage")
                    critique = stage.get("history", [{}])[-1].get("critique", "No details available.")
                    
                    report.append(f"### Fix for {section.get('section_id')} ({stage_name})")
                    report.append(f"> **Issue:** {critique}")
                    report.append(f"**Action Plan:**")
                    if "Article 12" in section.get("section_id"):
                        report.append("- Implement automated session logging for at least 6 months.")
                        report.append("- Ensure logs include timestamps, User IDs, and model parameters.")
                    elif "Article 13" in section.get("section_id"):
                        report.append("- Generate a system-card with accuracy and limitation metrics.")
                        report.append("- Add a 'Why did the AI say this?' feature for transparency.")
                    else:
                        report.append("- Update technical documentation to align with Annex IV requirements.")
                        report.append("- Perform a bias audit on your training datasets.")

        report.append(f"\n---\n*Report generated by RaiFlow - The Regulatory AI Guardrail Framework.*")
        return "\n".join(report)
