from __future__ import annotations

import importlib.resources
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import List

from raiflow.scanner import DetectionResult

# ── EU AI Act article lists ───────────────────────────────────────────────────

HIGH_ARTICLES: List[str] = [
    "Article 9",
    "Article 10",
    "Article 11",
    "Article 12",
    "Article 13",
    "Article 14",
]

LIMITED_ARTICLES: List[str] = ["Article 13"]

# ── Package data constants ────────────────────────────────────────────────────

WORKFLOW_RESOURCE_PACKAGE = "raiflow.data"
WORKFLOW_RESOURCE_NAME = "rai-compliance.yml"


# ── Data models ───────────────────────────────────────────────────────────────

@dataclass
class WriteResult:
    path: Path
    action: str  # "written" | "skipped" | "overwritten"


@dataclass
class SummaryResult:
    detection: DetectionResult
    write_results: List[WriteResult] = field(default_factory=list)


# ── Manifest rendering ────────────────────────────────────────────────────────

def render_manifest(detection: DetectionResult, system_name: str) -> str:
    """Return a raiflow.yaml string pre-filled from *detection*.

    Uses a raw string template (not yaml.dump) to preserve inline comments.
    The risk_level comment references the detected framework names.
    """
    articles = HIGH_ARTICLES if detection.risk_level == "high" else LIMITED_ARTICLES
    articles_yaml = "\n".join(f'  - "{a}"' for a in articles)

    model_name = detection.frameworks[0] if detection.frameworks else "my-ai-model"

    detected_comment = (
        "# detected: " + ", ".join(detection.frameworks)
        if detection.frameworks
        else "# no frameworks detected"
    )

    return rf"""# ============================================================
# raiflow.yaml — RaiFlow Compliance Manifest (auto-generated)
# ============================================================
# Generated by `raiflow init`. Edit the fields below to match
# your system. Run `raiflow check --stage ci` to validate.
# ============================================================

# system_name: human-readable identifier for your AI system
system_name: "{system_name}"

# risk_level: EU AI Act risk classification (high | limited | minimal)
risk_level: "{detection.risk_level}"  {detected_comment}

# compliance_framework: regulatory framework to enforce
# eu_ai_act | nist_ai_rmf | iso_42001
compliance_framework: "eu_ai_act"

# eu_ai_act_articles: articles enforced during compliance checks
eu_ai_act_articles:
{articles_yaml}

# model_metadata: information about the AI model powering this system
model_metadata:
  # name: unique identifier for the model (used in banned-model scanning)
  name: "{model_name}"
  # version: semantic version of the model artifact
  version: ""
  # disclosure_flag: assert that users are informed they interact with AI (Article 13)
  disclosure_flag: true

# risk_management: documents the risk management process (Article 9)
risk_management:
  # assessment_path: path to the risk assessment document
  assessment_path: "docs/risk_assessment.md"

# oversight: human-override endpoints (Article 14)
oversight:
  # override_endpoints: URL paths that allow operators to intervene
  override_endpoints:
    - "/api/override"
    - "/api/halt"

# logging: controls RaiFlow logging middleware (Article 12)
logging:
  # middleware_active: assert that the RaiFlow interceptor is mounted
  middleware_active: true

# data_governance: training/evaluation dataset metadata (Article 10)
data_governance:
  # dataset_path: path to the dataset file
  dataset_path: "data/training.csv"
  # format: file format of the dataset (csv, jsonl, parquet)
  format: "csv"
  # protected_attributes: column names representing protected characteristics
  protected_attributes:
    - "gender"
    - "ethnicity"
"""


# ── File writers ──────────────────────────────────────────────────────────────

def write_manifest(content: str, root: Path, force: bool) -> WriteResult:
    """Write *content* to *root*/raiflow.yaml.

    Returns WriteResult with action="skipped" if the file exists and force=False,
    "overwritten" if exists and force=True, "written" if new.
    """
    target = root / "raiflow.yaml"
    if target.exists():
        if not force:
            return WriteResult(path=target, action="skipped")
        target.write_text(content, encoding="utf-8", newline="")
        return WriteResult(path=target, action="overwritten")
    target.write_text(content, encoding="utf-8", newline="")
    return WriteResult(path=target, action="written")


def write_workflow(root: Path, force: bool) -> WriteResult:
    """Copy the canonical workflow template to *root*/.github/workflows/rai-compliance.yml.

    Reads the template via importlib.resources from raiflow.data.
    Creates .github/workflows/ if it does not exist.
    Returns WriteResult with action="skipped" if the file exists and force=False.
    Exits with code 1 to stderr if package data is missing.
    """
    try:
        content = (
            importlib.resources.files(WORKFLOW_RESOURCE_PACKAGE)
            .joinpath(WORKFLOW_RESOURCE_NAME)
            .read_text(encoding="utf-8")
        )
    except (FileNotFoundError, TypeError, AttributeError):
        print(
            f"Package data missing: {WORKFLOW_RESOURCE_NAME} — reinstall raiflow",
            file=sys.stderr,
        )
        sys.exit(1)

    workflows_dir = root / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)

    target = workflows_dir / WORKFLOW_RESOURCE_NAME
    if target.exists():
        if not force:
            return WriteResult(path=target, action="skipped")
        target.write_text(content, encoding="utf-8")
        return WriteResult(path=target, action="overwritten")
    target.write_text(content, encoding="utf-8")
    return WriteResult(path=target, action="written")


# ── Summary ───────────────────────────────────────────────────────────────────

def build_summary(detection: DetectionResult, write_results: List[WriteResult]) -> SummaryResult:
    """Assemble a SummaryResult from scan and write outcomes."""
    return SummaryResult(detection=detection, write_results=write_results)


def print_summary(summary: SummaryResult) -> None:
    """Print informational output to stdout; errors/warnings to stderr."""
    detection = summary.detection

    # Detected frameworks
    if detection.frameworks:
        print(f"Detected frameworks: {', '.join(detection.frameworks)}")
    else:
        print("No AI frameworks detected — verify risk_level manually.")

    # Inferred risk level
    print(f"Inferred risk level: {detection.risk_level}")

    # Written / overwritten files
    for wr in summary.write_results:
        if wr.action in ("written", "overwritten"):
            print(f"  {wr.action}: {wr.path}")

    # Skipped file notices
    for wr in summary.write_results:
        if wr.action == "skipped":
            print(f"  skipped (already exists, use --force to overwrite): {wr.path}")

    # Next step
    print("\nNext step: raiflow check --stage ci")
